### PR TITLE
Henrys work

### PR DESCRIPTION
**Pull request by birdday**
Clean PR. Dry run for working with pandas data frames and implementing proper unit tests.

### CODE REVIEW

**Comment by paulboone** [comment]
Ok, so what I think you're doing is you are intending to permanently switch to the *_new files but not yet. So the right way to do this is to branch master and push. If the commits are going go be ongoing for awhile and we want to do reviews during the process, you can branch FROM this new branch and set up PRs to the new branch. This is how you'd manage having an existing version of some software (say v 1.0) that you'd want to keep functional while you work on a new release (say v2.0). Then you can NOT add *_new files, and just make the necessary modifications to the old code so it is actually reviewable (because we can tell what lines changed). Does this make sense? It will be way easier.

**Comment by birdday** [comment]
You want me to branch the WilmerLab Master branch, and then PR to that (so basically a WilmerLab development branch), correct?

**Comment by paulboone** [comment]
Right. You can branch master (which is on Wilmerlab) and push to your repo. Then you can branch from that and PR to it. When the new branch is ready and we are ready to delete the old dictionary-based code (possibly multiple PRs), we will PR from the new branch to master.

**Comment by birdday** [comment]
Sounds good.

**Pull request closed without merging**
